dist: xenial
sudo: false
language: php

php:
  - 7.3
  - 7.4snapshot
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer install

script:
  - ./vendor/bin/phpunit

jobs:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

  include:
    - stage: Quality
      env: TEST_COVERAGE=1
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./vendor/bin/phpunit --coverage-clover ./clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

    - stage: Quality
      env: CODE_STYLE=1
      script:
        - ./vendor/bin/phpcs
